EvalConf:
  multi_object: True
  max_steps: 2000
  max_dist: 1.5
  is_gibson: False
  object_nav_path: "datasets/multiobject_episodes/"
  scene_path: "datasets/scene_datasets/"
  results_path: "results_multi_four/certainty_greed/"
  log_rerun: False
  n_agents: 4
  use_pointnav: False
  square_im: True
  mode: certainty
  fallback_mode: greedy
  sort_seed: -1

config: [
  ./controller_habitat.yaml, # Default Habitat Controller
  ./mapping_conf_sim.yaml,       # Default Mapping Configuration
  ./planning_conf.yaml       # Default Planning Configuration
]