EvalConf:
  multi_object: True
  max_steps: 750
  max_dist: 1.5
  is_gibson: False
  object_nav_path: "datasets/multiobject_episodes/"
  scene_path: "datasets/scene_datasets/"
  results_path: "results_multi_three/div_greed/"
  log_rerun: False
  n_agents: 3
  use_pointnav: False
  square_im: True
  mode: diversity
  fallback_mode: greedy

config: [
  ./controller_habitat.yaml, # Default Habitat Controller
  ./mapping_conf_sim.yaml,       # Default Mapping Configuration
  ./planning_conf.yaml       # Default Planning Configuration
]